name: create branch & pull request

on:
  pull_request:
    branches: [develop]

jobs:
  merge-dependabot-PR:
    permissions:
      actions: write
      checks: write
      contents: write
      # deployments: write
      # issues: write
      # packages: write
      pull-requests: write
      # repository-projects: write
      # security-events: write
      # statuses: write
    runs-on: ubuntu-latest

    steps:
      # develop ブランチをチェックアウトする
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      # ブランチが存在するかしないか判定
      - name: Check if branch exists
        id: branch_exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="develop-$(TZ=Asia/Tokyo date +'%Y%m%d')"
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "Branch already exists"
            echo "::set-output name=branch_name::"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_name::$BRANCH_NAME"
          fi

      # ブランチが存在しない場合は、作成・プッシュする
      - name: Create Branch and Push
        id: create_branch
        if: steps.branch_exists.outputs.branch_name != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.branch_exists.outputs.branch_name }}"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      # ブランチが存在する場合は、最新のdevelopブランチをrebaseする
      - name: Rebase latest develop branch
        if: steps.branch_exists.outputs.branch_name != ''
        run: |
          git remote update
          git checkout develop
          git pull
          git checkout ${{ steps.branch_exists.outputs.branch_name }}
          git rebase develop
          git push -f origin ${{ steps.branch_exists.outputs.branch_name }}

      # プルリクエストのbaseブランチを変更する
      - name: Run GitHub API
        run: |
          BRANCH_NAME="${{ steps.branch_exists.outputs.branch_name }}"
          curl -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                -d "{ \"base\": \"$BRANCH_NAME\" }" \

      # マージする
      - name: Enable auto-merge for Dependabot PRs
        # if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
