name: create branch & pull request

on:
  pull_request:
    branches: [develop]

env:
  BRANCH_NAME: "develop-$(TZ=Asia/Tokyo date +'%Y%m%d')"

jobs:
  merge-dependabot-PR:
    if: contains(github.head_ref, 'dependabot')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      # develop ブランチをチェックアウトする
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      # ブランチが存在するかしないか判定
      - name: Check if branch exists
        id: branch_exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "Branch already exists"
            echo "::set-output name=branch_name::"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_name::$BRANCH_NAME"
          fi

      # ブランチが存在しない場合は、作成・プッシュする
      - name: Create Branch and Push
        id: create_branch
        if: steps.branch_exists.outputs.branch_name != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      # プルリクエストのbaseブランチを変更する
      - name: Run GitHub API
        run: |
          BRANCH_NAME="develop-$(TZ=Asia/Tokyo date +'%Y%m%d')"
          curl -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                -d "{ \"base\": \"$BRANCH_NAME\" }" \

      # マージする
      - name: Enable auto-merge for Dependabot PRs
        # if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
