name: create branch & pull request

on:
  push:
    branches: [develop]

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      # develop ブランチをチェックアウトする
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      # ブランチが存在しない場合は作成する
      - name: Check if branch exists
        id: branch_exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="release_$(date +'%Y%m%d')"
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "Branch already exists"
            echo "::set-output name=branch_name::"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_name::$BRANCH_NAME"
          fi

      - name: Create Branch
        id: create_branch
        if: steps.branch_exists.outputs.branch_name != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.branch_exists.outputs.branch_name }}"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"
