name: create branch & pull request

on:
  push:
    branches: [develop]

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      # develop ブランチをチェックアウトする
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      # ブランチが存在しない場合は作成し、存在する場合は最新のdevelopブランチをマージする
      - name: Create Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_branch
        run: |
          BRANCH_NAME="release_$(date +'%Y%m%d')"
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "Branch already exists"
            git checkout "$BRANCH_NAME"
            git merge origin/develop
          else
            echo "Branch does not exist"
            git checkout -b "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
          fi
          echo "::set-output name=branch_name::$BRANCH_NAME"
